"""
config.py — Central configuration for EDA Agent.

Loads environment variables, defines paths, and holds project-wide constants.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env from project root (or wherever the user placed it)
load_dotenv()

# ── Paths ─────────────────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

# Knowledge base markdown (place in data/ or project root)
KB_PATH = DATA_DIR / "virtuoso_bridge_knowledge_base.md"

# Scan dataset (generated by tools/scan_libraries.py)
DATASET_PATH = DATA_DIR / "library_scan_dataset.json"

# Runtime error log
ERROR_LOG_PATH = DATA_DIR / "agent_errors.log"

# ── Design Constants ──────────────────────────────────────────────────────

DEFAULT_REF_LIB = "tsmcN65"

# System libraries excluded from scanning
SYSTEM_LIBS = {"tsmcN65", "analogLib", "sample", "basic", "ahdlLib"}

# ── LLM Settings ─────────────────────────────────────────────────────────

LLM_PROVIDER = os.environ.get("LLM_PROVIDER", "gemini_adc")

# Agent retry limit per task
MAX_RETRIES = 3
